# coding: utf-8

"""
    Neurovault API

    All ur images r belong to us  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from neurovault_sdk.paths.api_collections_id_atlases_.post import CollectionsAtlasesCreate
from neurovault_sdk.paths.api_collections_id_atlases_.get import CollectionsAtlasesRetrieve
from neurovault_sdk.paths.api_collections_.post import CollectionsCreate
from neurovault_sdk.paths.api_collections_id_datatable_.get import CollectionsDatatableRetrieve
from neurovault_sdk.paths.api_collections_id_.delete import CollectionsDestroy
from neurovault_sdk.paths.api_collections_id_images_.post import CollectionsImagesCreate
from neurovault_sdk.paths.api_collections_id_images_.get import CollectionsImagesRetrieve
from neurovault_sdk.paths.api_collections_.get import CollectionsList
from neurovault_sdk.paths.api_collections_id_nidm_results_.post import CollectionsNidmResultsCreate
from neurovault_sdk.paths.api_collections_id_nidm_results_.get import CollectionsNidmResultsRetrieve
from neurovault_sdk.paths.api_collections_id_.patch import CollectionsPartialUpdate
from neurovault_sdk.paths.api_collections_id_.get import CollectionsRetrieve
from neurovault_sdk.paths.api_collections_id_.put import CollectionsUpdate


class CollectionsApi(
    CollectionsAtlasesCreate,
    CollectionsAtlasesRetrieve,
    CollectionsCreate,
    CollectionsDatatableRetrieve,
    CollectionsDestroy,
    CollectionsImagesCreate,
    CollectionsImagesRetrieve,
    CollectionsList,
    CollectionsNidmResultsCreate,
    CollectionsNidmResultsRetrieve,
    CollectionsPartialUpdate,
    CollectionsRetrieve,
    CollectionsUpdate,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
