# coding: utf-8

"""
    Neurovault API

    All ur images r belong to us  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from neurovault_sdk.paths.api_images_id_datatable_.get import ImagesDatatableRetrieve
from neurovault_sdk.paths.api_images_id_.delete import ImagesDestroy
from neurovault_sdk.paths.api_images_.get import ImagesList
from neurovault_sdk.paths.api_images_id_.patch import ImagesPartialUpdate
from neurovault_sdk.paths.api_images_id_.get import ImagesRetrieve
from neurovault_sdk.paths.api_images_id_.put import ImagesUpdate


class ImagesApi(
    ImagesDatatableRetrieve,
    ImagesDestroy,
    ImagesList,
    ImagesPartialUpdate,
    ImagesRetrieve,
    ImagesUpdate,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
