# coding: utf-8

"""
    Neurovault API

    All ur images r belong to us  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import neurovault_sdk
from neurovault_sdk.model.patched_image import PatchedImage
from neurovault_sdk import configuration


class TestPatchedImage(unittest.TestCase):
    """PatchedImage unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
